import { ColorToken, SpacingToken, TypographyToken } from '../types/design-system';

export const OVEQIRA_BRAND = {
  name: 'OVEQIRA',
  tagline: 'Digital Growth Partner',
  descriptor: 'Premium Digital Studio + Technology Company + Strategic Growth Partner',
  positioning: 'Strategic. Modern. Intelligent. Premium. Technical. Reliable. Human.',
  principle: 'Less visual noise. More visual intention.',
  coreCapabilities: [
    'Web Design & Development',
    'UI/UX Design',
    'SEO & Organic Strategy',
    'Digital Marketing',
    'Google Ads & PPC',
    'Meta Ads & Performance',
    'Social Media Growth',
    'Photography & Videography',
    'AI Solutions & Automation',
    'Custom Digital Products',
  ],
};

export const COLOR_TOKENS: ColorToken[] = [
  {
    name: 'Background Base',
    variable: '--background',
    lightValue: '#FFFFFF',
    darkValue: '#0A0A0A',
    role: 'Primary canvas and main container background',
    contrastRatio: '21:1 against foreground',
  },
  {
    name: 'Background Secondary',
    variable: '--background-secondary',
    lightValue: '#F8F9FA',
    darkValue: '#18181B',
    role: 'Subtle section alternation and background variations',
    contrastRatio: '18.5:1 against foreground',
  },
  {
    name: 'Foreground (Text)',
    variable: '--foreground',
    lightValue: '#09090B',
    darkValue: '#F4F4F5',
    role: 'Primary high-contrast headings, main content, strong text',
    contrastRatio: '19.2:1 against canvas',
  },
  {
    name: 'Foreground Muted',
    variable: '--foreground-muted',
    lightValue: '#5A6170',
    darkValue: '#A1A1AA',
    role: 'Secondary body text, supporting paragraphs, subtitles',
    contrastRatio: '6.8:1 (WCAG AA Compliant)',
  },
  {
    name: 'Foreground Subtle',
    variable: '--foreground-subtle',
    lightValue: '#8E95A2',
    darkValue: '#71717A',
    role: 'Captions, technical coordinate labels, timestamps, metadata',
    contrastRatio: '4.6:1 (WCAG AA Compliant)',
  },
  {
    name: 'Border Base',
    variable: '--border',
    lightValue: '#E4E4E7',
    darkValue: '#27272A',
    role: 'Thin hairline dividers, card containers, subtle grid lines',
    contrastRatio: 'Subtle 1px structural framing',
  },
  {
    name: 'Border Strong',
    variable: '--border-strong',
    lightValue: '#D4D4D8',
    darkValue: '#3F3F46',
    role: 'Active input borders, emphasized cards, interactive bounds',
    contrastRatio: 'Definitive edge contrast',
  },
  {
    name: 'Surface',
    variable: '--surface',
    lightValue: '#FFFFFF',
    darkValue: '#18181B',
    role: 'Card background, elevated panel, modal surface',
    contrastRatio: 'Mathematically balanced elevation',
  },
  {
    name: 'Surface Hover',
    variable: '--surface-hover',
    lightValue: '#F4F4F5',
    darkValue: '#1A202E',
    role: 'Interactive hover feedback for cards and row items',
    contrastRatio: 'Refined 4% delta feedback',
  },
  {
    name: 'Accent (Signature)',
    variable: '--accent',
    lightValue: '#00A3B4', // High-contrast technical teal for light mode (WCAG AA)
    darkValue: '#00F5FF', // Signature electric cyan for dark mode
    role: 'Strategic signals: primary CTA accent, active indicators, metrics',
    contrastRatio: 'Calculated for AA accessibility in each surface mode',
  },
  {
    name: 'Accent Hover',
    variable: '--accent-hover',
    lightValue: '#008B9A',
    darkValue: '#22D3EE',
    role: 'Hover state for primary action buttons and links',
    contrastRatio: 'Enhanced saturation interaction',
  },
  {
    name: 'Accent Muted',
    variable: '--accent-muted',
    lightValue: 'rgba(0, 163, 180, 0.12)',
    darkValue: 'rgba(0, 242, 254, 0.12)',
    role: 'Subtle badge backgrounds, indicator halos, selection states',
    contrastRatio: 'Restrained non-distracting highlight',
  },
];

export const SPACING_TOKENS: SpacingToken[] = [
  { name: 'XS', size: '4px', px: 4, rem: '0.25rem', usage: 'Fine alignments, badge padding, icon gap' },
  { name: 'SM', size: '8px', px: 8, rem: '0.5rem', usage: 'Button vertical padding, compact gaps, form margins' },
  { name: 'MD', size: '16px', px: 16, rem: '1rem', usage: 'Card inner spacing, button horizontal padding, standard gap' },
  { name: 'LG', size: '24px', px: 24, rem: '1.5rem', usage: 'Editorial card padding, section gap grouping' },
  { name: 'XL', size: '32px', px: 32, rem: '2rem', usage: 'Sub-section separation, large card inner spacing' },
  { name: '2XL', size: '48px', px: 48, rem: '3rem', usage: 'Standard section rhythm, header margin' },
  { name: '3XL', size: '64px', px: 64, rem: '4rem', usage: 'Major editorial content division' },
  { name: '4XL', size: '96px', px: 96, rem: '6rem', usage: 'Hero vertical breathing room, flagship section separation' },
];

export const TYPOGRAPHY_TOKENS: TypographyToken[] = [
  {
    name: 'Display',
    tag: 'h1',
    desktopSize: '84px / 5.25rem',
    mobileSize: '64px / 4rem',
    lineHeight: '0.88',
    weight: '700 (Bold)',
    letterSpacing: '-0.035em',
    usage: 'Flagship hero headline, key brand moments with editorial confidence',
  },
  {
    name: 'H1',
    tag: 'h1',
    desktopSize: '48px / 3rem',
    mobileSize: '32px / 2rem',
    lineHeight: '1.15',
    weight: '700 (Bold)',
    letterSpacing: '-0.03em',
    usage: 'Major section titles, case study names, primary page headings',
  },
  {
    name: 'H2',
    tag: 'h2',
    desktopSize: '36px / 2.25rem',
    mobileSize: '26px / 1.625rem',
    lineHeight: '1.2',
    weight: '600 (Semibold)',
    letterSpacing: '-0.025em',
    usage: 'Sub-section titles, capability groupings, category headings',
  },
  {
    name: 'H3',
    tag: 'h3',
    desktopSize: '24px / 1.5rem',
    mobileSize: '20px / 1.25rem',
    lineHeight: '1.3',
    weight: '600 (Semibold)',
    letterSpacing: '-0.02em',
    usage: 'Card titles, service module headlines, metric headers',
  },
  {
    name: 'H4',
    tag: 'h4',
    desktopSize: '18px / 1.125rem',
    mobileSize: '16px / 1rem',
    lineHeight: '1.4',
    weight: '600 (Semibold)',
    letterSpacing: '-0.01em',
    usage: 'Feature headers, list titles, granular module names',
  },
  {
    name: 'Body Large',
    tag: 'p',
    desktopSize: '18px / 1.125rem',
    mobileSize: '16px / 1rem',
    lineHeight: '1.6',
    weight: '400 (Regular)',
    letterSpacing: '-0.01em',
    usage: 'Introductory lead text, value proposition paragraphs, editorial lead-ins',
  },
  {
    name: 'Body',
    tag: 'p',
    desktopSize: '16px / 1rem',
    mobileSize: '15px / 0.9375rem',
    lineHeight: '1.65',
    weight: '400 (Regular)',
    letterSpacing: '0',
    usage: 'Standard readable narrative, explanations, descriptions (65–75ch constrained)',
  },
  {
    name: 'Body Small',
    tag: 'p',
    desktopSize: '14px / 0.875rem',
    mobileSize: '13px / 0.8125rem',
    lineHeight: '1.5',
    weight: '400 (Regular)',
    letterSpacing: '0',
    usage: 'Secondary notes, card body text, supplementary explanations',
  },
  {
    name: 'Caption',
    tag: 'span',
    desktopSize: '12px / 0.75rem',
    mobileSize: '11px / 0.6875rem',
    lineHeight: '1.4',
    weight: '500 (Medium)',
    letterSpacing: '0.02em',
    usage: 'Timestamps, footnotes, technical specs, data point labels',
  },
  {
    name: 'Eyebrow / Technical Label',
    tag: 'span',
    desktopSize: '11px / 0.6875rem',
    mobileSize: '10px / 0.625rem',
    lineHeight: '1',
    weight: '600 (Semibold Mono)',
    letterSpacing: '0.12em (Uppercase)',
    usage: 'Section markers, status indicators, system coordinates (e.g. 01 // CAPABILITIES)',
  },
  {
    name: 'Button Label',
    tag: 'span',
    desktopSize: '14px / 0.875rem',
    mobileSize: '13px / 0.8125rem',
    lineHeight: '1',
    weight: '600 (Semibold)',
    letterSpacing: '-0.01em',
    usage: 'Interactive CTA labels, navigation links, action triggers',
  },
];

export const RADIUS_TOKENS = [
  { name: 'none', value: '0px', usage: 'Sharp technical dividers, flush full-bleed media' },
  { name: 'sm', value: '4px', usage: 'Buttons, inputs, compact tags, technical badges' },
  { name: 'md', value: '6px', usage: 'Default card border radius, modal container corners' },
  { name: 'lg', value: '8px', usage: 'Large editorial containers, media frames' },
  { name: 'full', value: '9999px', usage: 'Exclusively for status pills and counter badges' },
];

export const MOTION_TOKENS = {
  durations: {
    instant: 0.1,
    fast: 0.18,
    standard: 0.28,
    slow: 0.45,
  },
  easings: {
    default: [0.16, 1, 0.3, 1], // Custom cubic bezier: fast out, gentle settle
    sharp: [0.4, 0, 0.2, 1],
    smooth: [0.25, 0.1, 0.25, 1],
  },
};
